### ISSUE TITLE
NullPointerException for generating Flora

### ISSUE THREAD

**Issue by pollend** [Terasology/Lost#9]
```
15:17:03.248 [Chunk-Generator-1] ERROR o.t.u.concurrency.TaskProcessor - Error in thread Chunk-Generator-1
java.lang.NullPointerException: null
	at org.terasology.gf.generator.FloraFeatureGenerator.getDefinitionsForBiome(FloraFeatureGenerator.java:198)
	at org.terasology.gf.generator.FloraFeatureGenerator.generateChunk(FloraFeatureGenerator.java:131)
	at org.terasology.world.generation.WorldImpl.rasterizeChunk(WorldImpl.java:64)
	at org.terasology.world.generation.BaseFacetedWorldGenerator.createChunk(BaseFacetedWorldGenerator.java:75)
	at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider$1.run(LocalChunkProvider.java:649)
	at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
15:17:03.386 [Chunk-Generator-3] ERROR o.t.u.concurrency.TaskProcessor - Error in thread Chunk-Generator-3
java.lang.NullPointerException: null
	at org.terasology.gf.generator.FloraFeatureGenerator.getDefinitionsForBiome(FloraFeatureGenerator.java:198)
	at org.terasology.gf.generator.FloraFeatureGenerator.generateChunk(FloraFeatureGenerator.java:131)
	at org.terasology.world.generation.WorldImpl.rasterizeChunk(WorldImpl.java:64)
	at org.terasology.world.generation.BaseFacetedWorldGenerator.createChunk(BaseFacetedWorldGenerator.java:75)
	at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider$1.run(LocalChunkProvider.java:649)
	at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pollend** [comment]
https://gist.github.com/pollend/7650ae5c91ef09b6718956fdf527ed0a

**Comment by meetcshah19** [comment]
That FloraFeatureGenerator is no longer used. We should close this.

**Comment by jdrueckert** [comment]
Moved to https://github.com/Terasology/GrowingFlora/issues/18
